config/routes.rb
RedditClone::Application.routes.draw do
  resources :posts do 
      resources :comments
  end

  get '/posts/vote/upvote/:id', to: 'posts#up_vote'
  get '/posts/vote/downvote/:id', to: 'posts#down_vote'

  root to: "posts#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments
	belongs_to :users
	has_many :urls
	accepts_nested_attributes_for :comments
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
	has_many :comments, through: :posts
	has_many :votes
	has_many :posts, through: :votes
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_filter :load_post
  def index
    @comments = @post.comments.all.order(:description).reverse
    @user = current_user
  end

  def show
    @comment = @post.comments.find(params[:id])
  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = @post.comments.new(comment_params)
    if @comment.save
      redirect_to post_comments_path(@post)
    else
      render 'new'
    end
  end

  def destroy
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_comments_path(@post)
  end

private
  def comment_params
    params.require(:comment).permit(:description)
  end

  # create this method so we don't need the below line in every comments method
  def load_post
    @post = Post.find(params[:post_id])
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	def index
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    # if user_signed_in?
      @posts = Post.all
    # else
    #   redirect_to "root_path"
    # end
  end

  def up_vote
    @post = Post.increment_counter(:upvote, params[:id])
    redirect_to post_comments_path(@post)
  end

  def down_vote
    @post = Post.decrement_counter(:downvote, params[:id])
    redirect_to post_comments_path(@post)
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  def create
    @post = Post.create(post_params)
    redirect_to posts_path
  end

private
  def post_params
    params[:post].permit(:title, :description, :url, :comments_attributes=>[:description])
  end

end

app/controllers/user_controller.rb
class UsersController < ApplicationController

  
  def index
    @user = current_user
  end


private
  def user_params
    params.require(:user).permit(:email)
  end
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_test %><br>
    <%= f.text_field :post_test %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Title: <%= @post.title %></h1>
User: <%= @user.email %></br>
Description: <%= @post.description %></br>
Url: <%= link_to @post.url %>
<br></br>
<button type="button" class="btn btn-success"><%= link_to @post.upvote %></button>
  <%= link_to "Like", "/posts/vote/upvote/#{@post.id}", :class => 'btn btn-info' %>
  <%= link_to "Dislike", "/posts/vote/downvote/#{@post.id}", :class => 'btn btn-info' %>
  <button type="button" class="btn btn-danger"><%= link_to @post.downvote %></button>
<br></br>
<p>Comments</p>
<% @comments.each do |comment|%>
  <%=comment.description%>
    <%= link_to "Show", post_comment_path(@post, comment), :class => 'btn btn-default' %>
    <%= link_to "Delete", [@post, comment], method: :delete, data: {confirm: "Are You Sure?"}, :class => 'btn btn-danger' %></br>
  
  
<% end %>
<br></br>
<p><%= link_to "Comment On This Item", new_post_comment_path(@post), :class=>"btn btn-info" %>
</p>

<%= link_to 'Back to post', post_path(@post) %>

app/views/comments/new.html.erb
<h1>Create A New Comment</h1>

<%= form_for ([@post, @comment]) do |f| %>
  <%= f.text_field :description, placeholder: "Comment!" %>
  
  <%= f.submit %>

<% end %>

app/views/comments/show.html.erb
<h1><%=@post.title%></h1>


<%=@comment.description%></br>
<%= link_to 'Back', post_comments_path(@post) %>

app/views/dashboard/index.html.erb
<h1> Welcome to Dashboard </h1>

app/views/home/index.html.erb
<h1> Welcome to your home page </h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedditClone</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sub_post %><br>
    <%= f.text_field :sub_post %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :comment_id %><br>
    <%= f.text_field :comment_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Posts</h1>


<% @posts.each do |post| %>
  <li><%= link_to post.title, post_comments_path(post)%>
    <% count = 0%>
    <% post.comments.each do |comment| %>
      <% count += 1%>
  <% end %></br> 

  Comment Count: <%= link_to "#{count} comments", post_comments_path(post)%>
  <br></br> 

 
<% end %>

app/views/posts/new.html.erb
<h1>Create A New Post</h1>

<%= form_for @post do |f| %>
  <%= f.text_field :title, placeholder: "Name Of Item" %>
  <%= f.text_field :description, placeholder: "Description" %>
  <%= f.text_field :url, placeholder: "Url" %>

  <!-- build is used with relationships/associations -->
  <%= f.fields_for :comments, @post.comments.build do |b| %>
  <%= b.text_field :description, placeholder: "New Comment: " %>
  <% end %>
  <%= f.submit %>

<% end %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @post.title %></h1>
<h2><%= @post.description %></h2>

<p>
  <strong>Sub post:</strong>
  <%= @post.sub_post %>
</p>

<p>
  <strong>Link:</strong>
  <%= @post.link %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user_id %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @post.comment_id %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>